#%RAML 1.0
version: 1.0.0
title: deltaflightsbydestination
baseUri: http://localhost:8081/api
/deltaflightsbydestination: 
 get: 
  queryParameters: 
   destination:
    maxLength: 3
    minLength: 3
  responses: 
   200: 
    body: 
     application/json:
      example: !include example/deltaflightsbydestination.json
/addDeltafligts: 
  post: 
   body: 
     application/json:
   responses:
       201:
        body: 
         application/json: 
         
          
       
       